# Board
GRID_ROWS            = 25
GRID_COLUMNS         = 25
GRID_MINE_PERCENTAGE = 0.01

# Size of cells
CELL_SIZE = 25
CELL_BORDER = 2

# Colors
BACKGROUND_COLOR   = (26, 26, 26)
BORDER_COLOR       = (100, 100, 100)
TEXT_COLOR         = (255, 255, 255)
ONE_COLOR          = (255, 255, 255)
UNDISCOVERED_COLOR = (160, 160, 160)

# Cells
MINE         = -2
UNDISCOVERED = -1
EMPTY        =  0
ONE_MINE     =  1
TWO_MINES    =  2
THREE_MINES  =  3
FOUR_MINES   =  4
FIVE_MINES   =  5
SIX_MINES    =  6
SEVEN_MINES  =  7
EIGHT_MINES  =  8

# Window
PADDING       = 20
SCREEN_WIDTH  = (2 * PADDING + CELL_BORDER + GRID_COLUMNS * (CELL_SIZE + CELL_BORDER))
SCREEN_HEIGHT = (2 * PADDING + CELL_BORDER + GRID_ROWS * (CELL_SIZE + CELL_BORDER))
